### ISSUE TITLE
Nonunique subheadings link incorrectly

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/docs#15]
There is a fix for this in the [lord/slate `master` branch](https://github.com/lord/slate/commit/4f915e9cb2bc4e879016e8c990f0c00b68e37d71). @wanderingstan is there a convenient way to fast-forward our branch to include some of their changes, or would you like me to make a PR with the `NestingUniqueHeadCounter` class manually added? I've tested and it fixes our problem.

![nonunique-h2](https://user-images.githubusercontent.com/273937/39326754-9e649cea-495b-11e8-82fd-5bd3c4da06b1.gif)

**Comment by DanielVF** [comment]
Can we just copy their code over, and make a single commit here with the latest slate stuff?

**Comment by DanielVF** [comment]
Also, issue gif is the best thing since sliced bread.

**Comment by micahalcorn** [comment]
@wanderingstan https://github.com/OriginProtocol/docs/commit/8e64720daa3dbb942e17f6cd0450ba2fb7a31c56 thanks!

**Comment by wanderingstan** [comment]
Done and deployed! http://docs.originprotocol.com/#purchase-get

@micahalcorn is there a tool for making issue gifs?? I now feel like a caveman over here banging keys on my keyboard.

**Comment by micahalcorn** [comment]
@wanderingstan I just use [GIPHY Capture](https://giphy.com/apps/giphycapture), save, and drag into the comment box. There may be an easier way.

**Comment by wanderingstan** [comment]
Thanks!
![apr-27-2018 15-55-18](https://user-images.githubusercontent.com/673455/39386769-6d12f35c-4a33-11e8-826b-cf0ac2c02e93.gif)

**Comment by micahalcorn** [comment]
![perfection](https://user-images.githubusercontent.com/273937/39387180-c69636aa-4a3d-11e8-8db0-86c4c4d64c05.gif)
