### ISSUE TITLE
Detach from lord/slate

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/docs#4]
This repo gets "contaminated" with activity on the upstream [lord/slate](https://github.com/lord/slate) repo. 

We should detach it and make standalone.

**Comment by DanielVF** [comment]
Looks like GitHub took care of it - it's now a standalone repo. We'll want to change/remove the default template that comes up when you do a pull request, since it's out of date now.

**Comment by joshfraser** [comment]
Yep, updated the templates (https://github.com/OriginProtocol/docs/tree/master/.github)
