### ISSUE TITLE
Update css to better match website

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/docs#7]
A bigger makeover is needed someday, but for now the following would go a long way:
- Use Lato and Poppins fonts for body/headings
- Set background colors to match palette of company website. 

@micahalcorn - I know you're busy, but could you take stab at this? I can also do it.

**Comment by micahalcorn** [comment]
@wanderingstan certainly. It may be this evening, but otherwise no big deal.

**Comment by joshfraser** [comment]
Nice work on the docs. Looking way better.

Are you seeing the halo around the logo? Can we get rid of that?

**Comment by micahalcorn** [comment]
@joshfraser I did see that. It's actually part of the image file. I'll replace it and make another PR.

**Comment by wanderingstan** [comment]
This looks great, @micahalcorn . Than you!
